##  NUMPY PRACTICAL

# Creating NUMPY Arrays

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


# Creating NDArray Object

In [4]:
import numpy as np
arr = np.array((10,20,30,40))
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


# checking datatype of array

In [27]:
import numpy as np
arr = np.array((10,20,30,40))
print(arr.dtype)


int32


# Checking Number of Dimensions

In [7]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
arr3 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


# NUMPY Array Indexing

In [3]:
##Acessing Elements from Arrays

import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
arr3 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

print(arr1[2])           ##accesing element from 1d array
print(arr2[1,2])        ##accesing 2nd element from 1st dimension
print(arr3[0,1,1])      ##accesing  1st element of the second array of the first array

30
70
40


# Negative Indexing

In [4]:
##  we can also use the negative indexing to access the arrays like:-

import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([[10,20,30,40],[50,60,70,80]])

print(arr1[-2])
print(arr2[-2,-3])

30
20


##  Array Slicing

In [7]:
thisarray = np.array([10, 20, 30, 40, 50, 60, 70])

print(thisarray[3:])           #access the elements starting from the index 3 to the end of the array

print(thisarray[:3])           #access the elements from starting to the index 3 

print(thisarray[-4:-2]) #negative slicing
print(thisarray[2: : 2])


[40 50 60 70]
[10 20 30]
[40 50]
[30 50 70]


# Copy of an Array

In [8]:
thisarray = np.array([10, 20, 30, 40, 50, 60, 70])
arr = thisarray.copy()
thisarray[4] = 45
print(arr)

[10 20 30 40 50 60 70]


# View of an Array

In [16]:
thisarray = np.array([10, 20, 30, 40, 50, 60, 70])
arr = thisarray.copy()        ##copy doesn't affect the original array
thisarray[4] = 45
print(thisarray.view())       ##view represent the array after change
print(arr)

[10 20 30 40 45 60 70]
[10 20 30 40 50 60 70]


# NUMPY Sorting Arrays

In [21]:
thisarray = np.array(['apple','strawberry','papaya','banana','grapes'])
thisarray1 = np.array([30,2,57,10,90,34])
thisarray2 = np.array([[2,15,25,9,0],[12,9,0,25,4]])   ##sorting a 2d array
print(np.sort(thisarray))
print(np.sort(thisarray1))
print(np.sort(thisarray2))

['apple' 'banana' 'grapes' 'papaya' 'strawberry']
[ 2 10 30 34 57 90]
[[ 0  2  9 15 25]
 [ 0  4  9 12 25]]


# joining NUMPY Arrays

In [24]:
thisarray1 = np.array([10, 2, 3])

thisarray2 = np.array([4, 5, 6])

arr1 = np.concatenate((thisarray1, thisarray2))     ##add the content of both the arrays in a single array

arr2= np.stack((thisarray1, thisarray2), axis=0)    ##joining the array with stack function

arr3= np.stack((thisarray1, thisarray2), axis=1)

print(arr1)
print(arr2)
print(arr3)

[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]
[[10  4]
 [ 2  5]
 [ 3  6]]


# array split in Numpy

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Array Shape and Reshape

# Array Shape

In [15]:
import numpy as np
thisarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(thisarray.shape)
print(thisarray.size)
print(thisarray.nbytes)




(2, 4)
8
32


# array Reshape

In [21]:
import numpy as np

thisarray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = thisarray.reshape(3, 4)   ##reshape 1d array into 2d array
newarr2 = thisarray.reshape(2,3,2)   ##reshape 1d array into 3d array
print(newarr)
print(newarr2)
print(newarr.reshape(-1))     ##flattening  the array



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Searching in NUMPY Arrays

In [10]:
thisarray = np.array([25, 20, 30, 44, 35, 43, 43])

x = np.where(thisarray == 43)     ##the output show the index where value is exist

print(x)

(array([5, 6], dtype=int64),)


# Filtering Arrays

In [36]:
thisarray = np.array([10, 20, 30, 40])

x = [False, True, True, False]         ##In Filtering arrays value containing true included in the newarray and value containing false are excluded. 

newarray = thisarray[x]

print(newarray)

[20 30]


# Numpy Sum() function

In [24]:
import numpy as np
thisarray = np.array([2,6,8,3])
array_sum = np.sum(thisarray)      
print(array_sum)        ##sum of the elements in the given array

19


# Numpy zer0() function


In [25]:
import numpy as np
thisarray = np.zeros(5)
print(thisarray)

[0. 0. 0. 0. 0.]


# numpy ones() function

In [26]:
import numpy as np
thisarray = np.ones(4)
print(thisarray)

[1. 1. 1. 1.]
